backport string.*pack* from 5.3
moonjit/moonjit pull request #36
Opened 2019-11-19 20:57 UTC by fperrad

initially submitted as https://github.com/LuaJIT/LuaJIT/pull/269 and rejected.

I think that `moonjit` must be able to run Lua 5.3 code,
even if it is slow (and not jitable), even if someone thinks that the API is ugly.

2019-11-23 13:04 UTC, siddhesh requested changes
Thanks for the patch!  I've done a code review and nothing seems to pop out as obviously wrong.  I'd like to request a couple of changes though:

- Please fix the failing test `test/lib/contents.lua`.  You just need to add pack, packsize and unpack in the expected results string
- Please add a few simple smoke tests under `test/lib/string` for `string.*pack*` to confirm that basic functionality works as advertised.

2019-11-23 13:07 UTC, siddhesh commented
This seems like a nice feature to add to the 2.2 list, so I'm going to hold off 2.2 for a bit longer.

One more change: please update the documentation in https://github.com/moonjit/moonjit/blob/master/doc/extensions.md#extensions-from-lua-53

2019-11-23 14:28 UTC, joe-92 commented
Hi, I also have some annotations:

- Why define a own macro `MAX_SIZET` instead of using `MAX_SIZE` from `stdint.h`?
- I think it would be better to use the `LJ_BE` and `LJ_LE` defines instead of the union `nativeendian`.
- Why define a function `static int digit(int c)` instead of using `isdigit`?
- To maintain a similar style I think there should be a define `LUA_UNSIGNED` in `luaconf.h` and a corresponding typedef in `lua.h`. And the default `lua_Integer` type is `ptrdiff_t`, so maybe `size_t` would be a better choice for `lua_Unsigned`.

2019-11-25 18:48 UTC, fperrad commented
@joe-92 

> Hi, I also have some annotations:
> 
>     * Why define a own macro `MAX_SIZET` instead of using `MAX_SIZE` from `stdint.h`?
> 

Copy/Paste from PUC Lua, but I agree with you

>     * I think it would be better to use the `LJ_BE` and `LJ_LE` defines instead of the union `nativeendian`.
> 

I agree with you

>     * Why define a function `static int digit(int c)` instead of using `isdigit`?
> 

Copy/Paste from PUC Lua, but I disagree with you, `ctype.h` is never used in LuaJIT

>     * To maintain a similar style I think there should be a define `LUA_UNSIGNED` in `luaconf.h` and a corresponding typedef in `lua.h`. And the default `lua_Integer` type is `ptrdiff_t`, so maybe `size_t` would be a better choice for `lua_Unsigned`.

After some thinking, I propose to define `lua_Unsigned` inside `lib_string.c` instead of `lua.h`,
we don't need it in public interface.

2019-11-30 18:58 UTC, siddhesh commented
> After some thinking, I propose to define `lua_Unsigned` inside `lib_string.c` instead of `lua.h`,
> we don't need it in public interface.

It's defined in 5.2 specifically like below, so if you add it I think it should be in lua.h:

```
lua_Unsigned

typedef unsigned long lua_Unsigned;

The type used by the Lua API to represent unsigned integral values. It must have at least 32 bits.

By default it is an unsigned int or an unsigned long, whichever can hold 32-bit values. 
```

While the last line is a bit vague, the text as a whole indicates pretty clearly that `lua_Unsigned` is an `unsigned long`.

Also, please add your Signed-off-by in all the commits.

2019-11-30 19:28 UTC, fperrad commented
@siddhesh done

2019-11-30 19:34 UTC, joe-92 commented
On Win64 `unsigned long` is only 32bit wide, but `lua_Integer` is 64bit wide. Wouldn't this cause problems?

2019-12-01 04:21 UTC, siddhesh commented
The Lua 5.2 doc does not guarantee any consistency in size between `lua_Integer` and `lua_Unsigned`; both sizes are well defined to be inconsistent in 5.2 ;)

This has been resolved in 5.3 by adding more macros to make the whole setup more configurable and `lua_Unsigned` is simply defined as an unsigned type with the same storage as `lua_Integer`.  I suggest we keep the inconsistency the 5.2 way for now and then port in all of the integer configurations in one go in a separate PR.

2019-12-01 16:02 UTC, siddhesh approved these changes

2019-12-01 16:04 UTC, siddhesh commented
This looks fine for now.  I've created #63 to track the integer typedef issue.

2019-12-01 16:05 UTC, merged