backport utf8 library from 5.3
moonjit/moonjit pull request #38
Opened 2019-11-23 16:38 UTC by fperrad

initially submitted as https://github.com/LuaJIT/LuaJIT/pull/270 and rejected.

2019-11-29 04:29 UTC, fperrad commented
handle variant GC64

2019-12-08 10:12 UTC, siddhesh commented
Do you generate utf8.h in two parts, i.e. once for LJ_GC64 and once without and then build it?  This looks OK overall, but I suppose we need some mechanism to make sure that utf8.h gets updated when utf8.lua is.

Thanks to this I noticed Makefile.dep also needs to be manually updated (i.e. the `make depend` target doesn't get run automatically).  I'll pull this patch in as is and do something about these dependency issues later.

2019-12-08 10:31 UTC, siddhesh requested changes
A more thorough review this time:  Please re-post with the requested changes, which is basically documentation and more tests.

2019-12-08 10:31 UTC, siddhesh commented on src/lib_utf8.c
> +LUALIB_API int luaopen_utf8(lua_State *L)
This needs a mention in the documentation, i.e. not just the function but also the fact that we have the UTF8 library now.

2019-12-08 10:31 UTC, siddhesh commented on test/lib/contents.lua
> +  check(utf8, "char:charpattern:codepoint:codes:len:offset")
It would be nice to have some smoke tests that actually exercise the functions.

2019-12-08 15:40 UTC, fperrad commented
`utf8.h` must be generated in 2 parts, each one with a specific executable `luajit` (built with and without `-DLUAJIT_ENABLE_GC64`), so the target `utf8bc` cannot fully automatized this.

`host/buildvm_libbc.h` and the target `libbc` have the same limitations.

2019-12-09 07:44 UTC, siddhesh commented
> `utf8.h` must be generated in 2 parts, each one with a specific executable `luajit` (built with and without `-DLUAJIT_ENABLE_GC64`), so the target `utf8bc` cannot fully automatized this.

/me nods.  I was suggesting auto-generating every time, so that we don't have to keep track.  In any case, it's an orthogonal issue.  This PR itself only needs some documentation of the fact that we have utf8 library support and it's good to go.

2019-12-11 14:50 UTC, fperrad commented
doc and smoke tests added

5.4 version will come in another PR

2019-12-12 14:39 UTC, siddhesh approved these changes

2019-12-12 14:39 UTC, merged

2019-12-12 14:40 UTC, siddhesh commented
Thanks @fperrad