backport math.*integer from 5.3
moonjit/moonjit pull request #56
Opened 2019-11-27 11:04 UTC by fperrad

same behavior (and limitations) as lua-compat53

2019-11-28 17:03 UTC, fperrad commented
doc and smoke tests added

2019-12-08 11:24 UTC, siddhesh requested changes
Looks OK overall, just needs a bit more documentation.  Please add a bit in the documentation describing how number handling is limited in luajit and hence these math functions can handle only 53-bit integers, unlike lua which can do the full 64-bit integers when specified as integers.

2019-12-08 11:24 UTC, siddhesh commented on src/lib_math.c
> +LJLIB_PUSH(-9007199254740992) LJLIB_SET(mininteger)
I suppose that's an unfortunate limitation of always storing numbers as float; lua is able to convert all the way up to `2^63-1` both ways when the input is an integer (i.e. `9223372036854775807` and not `9223372036854775807.0`), which is what it should be.  Please mention this difference in the documentation, hopefully we can fix this up in future.

2019-12-08 11:24 UTC, siddhesh commented on src/lib_math.c
> +      if n <= 9007199254740992 and n >= -9007199254740992 and n % 1 == 0 then
Likewise, please mention the limitation in the documentation.

2019-12-08 16:05 UTC, fperrad commented
add limitations in extensions.md

2019-12-08 16:52 UTC, joe-92 commented
I can imagine that the functions `math.tointeger`, `math.type` and `math.ult` are often used, so wouldn't make it sense to add them as fast functions?

2019-12-09 13:51 UTC, siddhesh commented
The functions are compact enough that when jitted, they'll inline quite well and likely be more performant than C calls into fast functions.

2019-12-09 14:02 UTC, siddhesh approved these changes

2019-12-09 14:02 UTC, merged